server:
  port: 8041
springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: assignment-service
  datasource:
    url: jdbc:postgresql://postgres:5432/assignment_db
    username: president
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true